#index:
#    path: /
#    controller: App\Controller\DefaultController::index
download_ticket_pdf:
    path: /ticket/{id}/download/pdf
    controller: App\Controller\HomeController::downloadTicketPdf
forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityController::forgotPassword
pdf:
    path: /pdf
    controller: Dompdf:DevisController:pdf

